app/product/models.py
from app import db

from datetime import datetime


# class Product(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     image = db.Column(db.String(20), nullable=False, default='default.jpg.png')
#     name = db.Column(db.String(20), nullable=False)
#     price = db.Column(db.String, nullable=False)
#     discount = db.Column(db.String, nullable=False)
#     category = db.Column(db.String(20), nullable=False)
#     desc = db.Column(db.Text, nullable=False)
#     user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
#
#     def __repr__(self):
#         return '<Addproduct %r>' % self.name



#
# class Addproduct(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     name = db.Column(db.String(80), nullable=False)
#     price = db.Column(db.Numeric(10, 2), nullable=False)
#     discount = db.Column(db.Integer, default=0)
#     desc = db.Column(db.Text, nullable=False)
#     pub_date = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
#
#     brand_id = db.Column(db.Integer, db.ForeignKey('brand.id'), nullable=False)
#     brand = db.relationship('Brand', backref=db.backref('brands', lazy=True))
#
#     category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable=False)
#     category = db.relationship('Category', backref=db.backref('brands', lazy=True))
#
#     image = db.Column(db.String(150), nullable=False, default='image.jpg')
#
#     def __repr__(self):
#         return '<Addproduct %r>' % self.name
#
#
# class Brand(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     name = db.Column(db.String(30), nullable=False, unique=True)
#
#
# class Category(db.Model):
#     id = db.Column(db.Integer, primary_key=True)
#     name = db.Column(db.String(30), nullable=False, unique=True)

app/product/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length


class ProductForm(FlaskForm):
    image = FileField('Upload Image', validators=[FileAllowed(['jpg', 'png'])])
    name = StringField('Product Name', validators=[DataRequired(), Length(min=2, max=20)])
    price = StringField('Discount Price', validators=[DataRequired()])
    discount = StringField('Main Price', validators=[DataRequired()])
    category = StringField('Category', validators=[DataRequired(), Length(min=2, max=20)])
    desc = TextAreaField('Description', validators=[DataRequired()])
    submit = SubmitField('Post ')

app/blogs/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from flask_login import current_user, login_required
from app import db
from app.models import Blog, Gallery
from app.blogs.forms import BlogForm, GalleryForm, ProductForm, RecommendationForm
from app.blogs.utils import save_picture

blogs = Blueprint('blogs', __name__)


@blogs.route('/blogpost', methods=['GET', 'POST'])
def blogpost():
    global image_file
    form = BlogForm()
    if form.validate_on_submit():
        if form.image.data:
            picture_file = save_picture(form.image.data)
            image = picture_file
        title = form.title.data
        content = form.content.data
        author = current_user
        post = Blog(title=title, content=content, author=author, image=image)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('home'))
    elif request.method == 'GET':
        image_file = url_for('static', filename='img/' + Blog.image)
        image_file = url_for('static', filename='img/' + current_user.image_file)
    return render_template('blogpost.html', form=form, image_file=image_file)


@blogs.route('/image', methods=['GET', 'POST'])
@login_required
def image():
    global image_file
    form = GalleryForm()
    if form.validate_on_submit():
        if form.image.data:
            picture_file = save_picture(form.image.data)
            image = picture_file
        title = form.title.data
        content = form.content.data
        author = current_user
        gallery = Gallery(title=title, content=content, author=author, image=image)
        db.session.add(gallery)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('home'))
    elif request.method == 'GET':
        image_file = url_for('static', filename='img/' + Blog.image)
        image_file = url_for('static', filename='img/' + current_user.image_file)
    return render_template('image.html', form=form, image_file=image_file)


@blogs.route('/blog', methods=['GET', 'POST'])
@login_required
def blog():
    posts = Blog.query.all()
    return render_template("blog.html", posts=posts)


@blogs.route('/gallery', methods=['GET', 'POST'])
@login_required
def gallery():
    gallery = Gallery.query.all()
    return render_template("gallery.html", gallery=gallery)

app/main/routes.py
from flask import render_template, Blueprint, url_for, flash, redirect, request, abort, session, current_app, \
    make_response
from app.models import User, Product, Recommendation, Blog, Checkout
from app import db
from app.forms import CheckoutForm, ContactForm
from app import mail
from flask_mail import Message
from flask_login import current_user, login_required
import json
import pdfkit
import stripe
import secrets

main = Blueprint('main', __name__)

publishable_key = 'pk_test_51LsSTZIo0R5Gyt8Mim3vwte0jrXt378wpMlp2diEvHMViy5BApipWObHiuh6sfJo9Lsx6b9WDxqudhKm1IAHW6XU00PPXOfdB8'

stripe.api_key = 'sk_test_51LsSTZIo0R5Gyt8Mrn9IYB8F77kdlwzKoUTEFvOgtEP43bS0z1HUDYhlokv9YiX9Sh3WdGPI6hxQYEBq7gTmasUy00k1JNdoNj'








@main.route('/', methods=['GET', 'POST'])
def index():
    product = Product.query.all()
    recommendation = Recommendation.query.all()
    posts = Blog.query.all()
    return render_template("mainproducts.html", product=product, recommendation=recommendation, posts=posts)


@main.route('/checkout', methods=['GET', 'POST'])
@login_required
def checkout():
    if 'Shoppingcart' not in session or len(session['Shoppingcart']) <= 0:
        flash(f'please {current_user.username} add product to your cart to access this page...', 'warning')
        return redirect(url_for('product.product'))
    form = CheckoutForm()
    if form.validate_on_submit():
        try:
            subtotal = 0
            grandtotal = 0
            invoice = secrets.token_hex(5)
            customer_id = current_user.id
            product = Checkout.query.filter_by(customer_id=customer_id, invoice=invoice).order_by(
                Checkout.id.desc()).all()
            for key, product in session['Shoppingcart'].items():
                discount = 0
                discount = (discount / 100) * float(product['price'])

                subtotal += float(product['price'])
                subtotal -= discount

                grandtotal = float("%.2f" % (subtotal))
                user = Checkout(productsname=(product['name']), grandtotal=grandtotal, customer_id=current_user.id,
                                orders=session['Shoppingcart'], invoice=secrets.token_hex(5),
                                firstname=form.firstname.data, lastname=form.lastname.data, email=form.email.data,
                                phone=form.phone.data, country=form.country.data, city=form.city.data,
                                street=form.street.data, building=form.building.data, zip=form.zip.data,
                                date_created=form.date_created.data, description=form.description.data, )
            db.session.add(user)
            db.session.commit()
            flash('Your order has been sent successfully', 'success')
            return redirect(url_for('main.payment'))
        except Exception as e:
            print(e)
            flash('something went wrong while getting order', 'danger')
            return redirect(url_for('product.product'))

    subtotal = 0
    grandtotal = 0
    invoice = secrets.token_hex(5)
    customer_id = current_user.id
    customer = User.query.filter_by(id=customer_id).first()
    orders = Checkout.query.filter_by(customer_id=customer_id, invoice=invoice).order_by(
        Checkout.id.desc()).all()
    for key, product in session['Shoppingcart'].items():
        discount = 0
        discount = (discount / 100) * float(product['price'])

        subtotal += float(product['price'])
        subtotal -= discount

        grandtotal = ("%.2f" % float(subtotal))

    return render_template('checkout.html', title='Register', invoice=invoice, customer=customer, orders=orders,
                           form=form, grandtotal=grandtotal, product=product)



@main.route('/payment', methods=['GET', 'POST'])
@login_required
def payment():
    if payment and request.method == "POST":
        return redirect(url_for('main.thanks'))

    subtotal = 0
    grandtotal = 0
    invoice = secrets.token_hex(5)
    customer_id = current_user.id
    for key, product in session['Shoppingcart'].items():
        discount = 0
        discount = (discount / 100) * float(product['price'])

        subtotal += float(product['price'])
        subtotal -= discount

        grandtotal = ("%.2f" % float(subtotal))

    return render_template('payments.html', grandtotal=grandtotal)


@main.route('/thanks')
@login_required
def thanks():
    return render_template('thank.html')


@main.route('/faq', methods=['GET', 'POST'])
@login_required
def faq():
    return render_template("faq.html")


@main.route('/contact', methods=['GET', 'POST'])
@login_required
def contact():
    user = User
    form = ContactForm()
    if form.validate_on_submit():
        msg = Message(f'New Message from {current_user.username}', sender=f'{user.email}',
                      recipients=['eorji452@gmail.com'])
        msg.body = f"""
           Name :  {form.name.data}

           Email :  {form.contact_email.data}

           Subject :  {form.subject.data}

           Message :  {form.message.data}
           """
        mail.send(msg)
        flash('your message have been sent', 'success')
        return redirect(url_for('main.index'))
    return render_template('contact.html', title='contact Form', form=form)


@main.route('/get_pdf', methods=['GET', 'POST'])
@login_required
def get_pdf():
    if current_user.is_authenticated:
        invoice = secrets.token_hex(5)
        grandTotal = 0
        subTotal = 0
        customer_id = current_user.id
        if request.method == "POST":
            customer = User.query.filter_by(id=customer_id).first()
            orders = Checkout.query.filter_by(customer_id=customer_id).order_by(Checkout.id.desc()).first()
            for _key, product in session['Shoppingcart'].items():
                discount = 0
                discount = (discount / 100) * float(product['price'])
                subTotal += float(product['price'])
                subTotal -= discount
                tax = ("%.2f" % (.06 * float(subTotal)))
                grandTotal = ("%.2f" % float(subTotal))

            rendered = render_template('pdf.html', invoice=invoice, tax=tax, grandTotal=grandTotal, customer=customer,
                                       orders=orders)
            pdf = rendered
            response = make_response(pdf)

            response.headers['content-Type'] = 'application/pdf'
            response.headers['content-Disposition'] = 'atteched; filename=' + invoice + '.pdf'
            return response
    return redirect(url_for('main.checkout'))

app/order/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from app.models import Checkout
from flask_login import current_user, login_required

from app import db
order = Blueprint('order', __name__)


@order.route('/orders', methods=['GET', 'POST'])
@login_required
def orders():
    checkout = Checkout.query.all()
    return render_template('orders.html', checkout=checkout)


@order.route("/delete_order/<int:order_id>/delete", methods=['GET', 'POST'])
def delete_order(order_id):
    order = Checkout.query.get_or_404(order_id)
    if current_user.email != 'sativatrendy@gmail.com':
        abort(403)
    db.session.delete(order)
    db.session.commit()
    flash("the product has been deleted successfully", 'success')
    return redirect(url_for('admin.home'))
    return render_template("home.html", order=order)

app/product/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from app import db
from app.product.forms import ProductForm
from app.models import Blog, Product, Recommendation
from flask_login import current_user, login_required
from app.product.utils import save_picture

prod = Blueprint('product', __name__)


@prod.route('/productpost', methods=['GET', 'POST'])
@login_required
def productpost():
    global image_file
    form = ProductForm()
    if form.validate_on_submit():
        if form.image.data:
            picture_file = save_picture(form.image.data)
            image = picture_file
        name = form.name.data
        price = form.price.data
        discount = form.discount.data
        category = form.category.data
        desc = form.desc.data
        author = current_user
        product = Product(name=name, price=price, discount=discount, category=category, desc=desc, author=author, image=image)
        db.session.add(product)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('admin.home'))
    elif request.method == 'GET':
        image_file = url_for('static', filename='img/' + Blog.image)
        image_file = url_for('static', filename='img/' + current_user.image_file)
    return render_template('productpost.html', form=form, image_file=image_file)


@prod.route('/single_product', methods=['GET', 'POST'])
def single_product():
    product = Product.query.all()
    recommendation = Recommendation.query.all()
    return render_template('single_product.html', product=product, recommendation=recommendation)


@prod.route('/product', methods=['GET', 'POST'])
@login_required
def product():
    product = Product.query.all()
    return render_template("product.html", product=product)


@prod.route("/productpost/<int:product_id>", methods=['GET', 'POST'])
def products(product_id):
    prod = Product.query.get_or_404(product_id)
    return render_template("single_product.html", prod=prod)

app/recom/routes.py
from flask import render_template, url_for, flash, redirect, request, abort, Blueprint
from app import db
from app.recom.forms import RecommendationForm
from app.models import Blog, Product, Recommendation
from flask_login import current_user, login_required
from app.recom.utils import save_picture

recom = Blueprint('recom', __name__)


@recom.route('/recom', methods=['GET', 'POST'])
def recommendation():
    global image_file
    form = RecommendationForm()
    if form.validate_on_submit():
        if form.image.data:
            picture_file = save_picture(form.image.data)
            image = picture_file
        name = form.name.data
        price = form.price.data
        discount = form.discount.data
        category = form.category.data
        desc = form.desc.data
        author = current_user
        recommendation = Recommendation(name=name, price=price, discount=discount, category=category, desc=desc,
                                        author=author,
                                        image=image)
        db.session.add(recommendation)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('admin.home'))
    elif request.method == 'GET':
        image_file = url_for('static', filename='img/' + Blog.image)
        image_file = url_for('static', filename='img/' + current_user.image_file)
    return render_template('recommendation.html', form=form, image_file=image_file)


@recom.route("/recom/<int:recommendation_id>", methods=['GET', 'POST'])
def recommendations(recommendation_id):
    rec = Recommendation.query.get_or_404(recommendation_id)
    return render_template("single_rec.html", rec=rec)


@recom.route("/delete_rec/<int:rec_id>/delete", methods=['GET', 'POST'])
def delete_rec(rec_id):
    rec = Recommendation.query.get_or_404(rec_id)
    if current_user.email != 'sativatrendy@gmail.com':
        abort(403)
    db.session.delete(rec)
    db.session.commit()
    flash("the recommended product has been deleted successfully", 'success')
    return redirect(url_for('admin.home'))
    return render_template("home.html", rec=rec)


@recom.route("/delete_prod/<int:prod_id>/delete", methods=['GET', 'POST'])
def delete_prod(prod_id):
    prod = Product.query.get_or_404(prod_id)
    if current_user.email != 'sativatrendy@gmail.com':
        abort(403)
    db.session.delete(prod)
    db.session.commit()
    flash("the product has been deleted successfully", 'success')
    return redirect(url_for('admin.home'))
    return render_template("home.html", prod=prod)

app/templates/admin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Favicon icon -->
    <link rel="icon" type="image/png" sizes="16x16" href="static/assets/images/favicon.png">
    <title>Sir Trendy E-commerce</title>
    <!-- Bootstrap Core CSS -->
    <link href="static/assets/node_modules/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="static/assets/node_modules/perfect-scrollbar/css/perfect-scrollbar.css" rel="stylesheet">
    <!-- This page CSS -->
    <!-- chartist CSS -->
    <link href="static/static/assets/node_modules/morrisjs/morris.css" rel="stylesheet">
    <!--c3 CSS -->
    <link href="static/assets/node_modules/c3-master/c3.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="static/css/style.css" rel="stylesheet">
    <!-- Dashboard 1 Page CSS -->
    <link href="static/css/pages/dashboard1.css" rel="stylesheet">
    <!-- You can change the theme colors from here -->
    <link href="static/css/colors/default.css" id="theme" rel="stylesheet">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body class="fix-header fix-sidebar card-no-border">
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="loader">
            <div class="loader__figure"></div>
            <p class="loader__label">Emmanuel Admin Wrap</p>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">
        <!-- ============================================================== -->
        <!-- Topbar header - style you can find in pages.scss -->
        <!-- ============================================================== -->
        <header class="topbar">
            <nav class="navbar top-navbar navbar-expand-md navbar-light">
                <!-- ============================================================== -->
                <!-- Logo -->
                <!-- ============================================================== -->
                <div class="navbar-header">
                    <a class="navbar-brand" href="{{ url_for('main.index') }}">
                        <!-- Logo icon --><b>
                            <!--You can put here icon as well // <i class="wi wi-sunset"></i> //-->
                            <!-- Dark Logo icon -->
                            <img src="static/assets/images/logo-icon.png" alt="homepage" class="dark-logo" />
                            <!-- Light Logo icon -->
                            <img src="static/assets/images/logo-light-icon.png" alt="homepage" class="light-logo" />
                        </b>
                        <!--End Logo icon -->
                        <!-- Logo text --><span>
                         <!-- dark Logo text -->
                         <img src="static/assets/images/logo-text.png" alt="homepage" class="dark-logo" />
                         <!-- Light Logo text -->
                         <img src="static/assets/images/logo-light-text.png" class="light-logo" alt="homepage" /></span> </a>
                </div>
                <!-- ============================================================== -->
                <!-- End Logo -->
                <!-- ============================================================== -->
                <div class="navbar-collapse">
                    <!-- ============================================================== -->
                    <!-- toggle and nav items -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"> <a class="nav-link nav-toggler hidden-md-up waves-effect waves-dark" href="javascript:void(0)"><i class="fa fa-bars"></i></a> </li>
                        <!-- ============================================================== -->
                        <!-- Search -->
                        <!-- ============================================================== -->
                        <li class="nav-item hidden-xs-down search-box"> <a class="nav-link hidden-sm-down waves-effect waves-dark" href="javascript:void(0)"><i class="fa fa-search"></i></a>
                            <form class="app-search">
                                <input type="text" class="form-control" placeholder="Search & enter"> <a class="srh-btn"><i class="fa fa-times"></i></a></form>
                        </li>
                    </ul>
                    <!-- ============================================================== -->
                    <!-- User profile and search -->
                    <!-- ============================================================== -->
                    <ul class="navbar-nav my-lg-0">
                        <!-- ============================================================== -->
                        <!-- Profile -->
                        <!-- ============================================================== -->
                        <li class="nav-item dropdown u-pro">
                            <a class="nav-link dropdown-toggle waves-effect waves-dark profile-pic" href="" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="static/assets/images/users/1.jpg" alt="user" class="" /> <span class="hidden-md-down">Mark Sanders &nbsp;</span> </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- ============================================================== -->
        <!-- End Topbar header -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <aside class="left-sidebar">
            <!-- Sidebar scroll-->
            <div class="scroll-sidebar">
                <!-- Sidebar navigation-->
                <nav class="sidebar-nav">
                    <ul id="sidebarnav">
                        <li> <a class="waves-effect waves-dark" href="{{ url_for('admin.home') }}" aria-expanded="false"><i class="fa fa-tachometer"></i><span class="hide-menu">Dashboard</span></a>
                        </li>
                        <li> <a class="waves-effect waves-dark" href="{{ url_for('blogs.blogpost') }}" aria-expanded="false"><i class="fa fa-user-circle-o"></i><span class="hide-menu">Blog Post</span></a>
                        </li>
                        <li> <a class="waves-effect waves-dark" href="{{ url_for('blogs.image') }}" aria-expanded="false"><i class="fa fa-table"></i><span class="hide-menu">Image Post</span></a>
                        </li>
                        <li> <a class="waves-effect waves-dark" href="{{ url_for('product.productpost') }}" aria-expanded="false"><i class="fa fa-smile-o"></i><span class="hide-menu">Products Post</span></a>
                        </li>
                        <li> <a class="waves-effect waves-dark" href="{{ url_for('recom.recommendation') }}" aria-expanded="false"><i class="fa fa-globe"></i><span class="hide-menu">Recommendation</span></a>
                        </li>
                        <li> <a class="waves-effect waves-dark" href="{{ url_for('order.orders') }}" aria-expanded="false"><i class="fa fa-bookmark-o"></i><span class="hide-menu">Ordered products</span></a>
                        </li>
                    </ul>
                    <div class="text-center m-t-30">
                        <a href="{{ url_for('main.index') }}" class="btn waves-effect waves-light btn-info hidden-md-down">Back to Home page</a>
                    </div>
                </nav>
                <!-- End Sidebar navigation -->
            </div>
            <!-- End Sidebar scroll-->
        </aside>
        <!-- ============================================================== -->
        <!-- End Left Sidebar - style you can find in sidebar.scss  -->
        <!-- ============================================================== -->
        <!-- ============================================================== -->
        <!-- Page wrapper  -->
        <!-- ============================================================== -->
       {% block content %}
       {% endblock content %}
        <!-- ============================================================== -->
        <!-- End Page wrapper  -->
        <!-- ============================================================== -->
    </div>
    <!-- ============================================================== -->
    <!-- End Wrapper -->
    <!-- ============================================================== -->
    <!-- ============================================================== -->
    <!-- All Jquery -->
    <!-- ============================================================== -->
    <script src="static/assets/node_modules/jquery/jquery.min.js"></script>
    <!-- Bootstrap popper Core JavaScript -->
    <script src="static/assets/node_modules/bootstrap/js/popper.min.js"></script>
    <script src="static/assets/node_modules/bootstrap/js/bootstrap.min.js"></script>
    <!-- slimscrollbar scrollbar JavaScript -->
    <script src="static/js/perfect-scrollbar.jquery.min.js"></script>
    <!--Wave Effects -->
    <script src="static/js/waves.js"></script>
    <!--Menu sidebar -->
    <script src="static/js/sidebarmenu.js"></script>
    <!--Custom JavaScript -->
    <script src="static/js/custom.min.js"></script>
    <!-- ============================================================== -->
    <!-- This page plugins -->
    <!-- ============================================================== -->
    <!--morris JavaScript -->
    <script src="static/assets/node_modules/raphael/raphael-min.js"></script>
    <script src="static/assets/node_modules/morrisjs/morris.min.js"></script>
    <!--c3 JavaScript -->
    <script src="static/assets/node_modules/d3/d3.min.js"></script>
    <script src="static/assets/node_modules/c3-master/c3.min.js"></script>
    <!-- Chart JS -->
    <script src="static/js/dashboard1.js"></script>
</body>

</html>

app/templates/product.html
{% extends 'layout.html' %}
{% block content %}
    <hr class="offset-lg">

    <div class="container tags">

        <p>List of products available</p>
        <div class="btn-group" >
            <a class="" href="{{url_for('carts.cart')}}">cart ({{session['Shoppingcart']|length}})</a>
        </div>

    </div>

    <div class="container">
      <div class="row">
        <!-- Filter -->


        <!-- Products -->
        <div class="col-sm-12 products">
          <div style="align-items: center" class="row">
            {% for prod in product %}
            <div  class="col-sm-12 col-md-3  product">
                 <br>
              <a href="#favorites" class="favorites" data-favorite="inactive"><i class="ion-ios-heart-outline"></i></a>
              <a href="/catalog"><img src="{{url_for('static', filename='img/' + prod.image)}}" alt="HP Chromebook 11"/></a>

              <div class="content">
                <h1 class="h4">{{ prod.name }}</h1>
                <p class="price">${{ prod.price }}</p>

                  <p class="price through">${{ prod.discount }}</p>

                <label>{{ prod.category }}</label>
                  <div style="display: flex">
                <a href="{{ url_for('product.products', product_id=prod.id) }}" class="btn btn-link"> Details</a>
                <form action="{{ url_for('carts.AddCart') }}" method="POST" enctype="multipart/form-data">
                  <input type="hidden" name="product_id" value="{{prod.id}}">
                  <button type="submit" class="btn btn-primary btn-rounded"> 
                    <i class="ion-bag"></i> Add to cart</button>
                 
                  <input type="hidden" name="quantity" id=""  value="1" min="1" max="100">
                </form>
                  </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
        </div>
      </div>
    </div>
    <br><br>
{% endblock content %}